##########
# collectionbuilder-csv
# Jekyll Digital Collection Generator
# https://github.com/CollectionBuilder/collectionbuilder-csv
##########

url: https://hdlab.space
baseurl: /fanzines-argentinos
source-code: https://github.com/hdlabconicet/fanzines-argentinos

title: Fanzines argentinos
# tagline: a short phrase that will appear throughout the site in the top banner
description: "Colección de fanzines argentinos de la década del '90."
keywords: zines;fanzine;contracultura;anarquía;protesta;punk;okupa
author: hdlab-CONICET

# COLLECTION SETTINGS
metadata: metadatos-coleccion
# page generation settings [optional!]
# [optional: only used if you need to tweak CB defaults or generate from more than one data file]
# page_gen:
#   - data: 'demo-metadata'
#     template: 'item'
#     name: 'objectid'
#     dir: 'items'
#     extension: 'html' 
#     filter: 'objectid'  

organization-name: "HD LAB, IIBICRIT-CONICET"
organization-link: https://hdlab.space/
organization-logo-banner: /assets/img/hdlab.jpg
# organization-logo-nav: https://cdil.lib.uidaho.edu/assets/img/logo.png

lib-assets: /assets/lib
exclude: [docs/, Rakefile, README.md, LICENSE, CITATION.cff, CODE_OF_CONDUCT.md, CONTRIBUTING.md, SECURITY.md]
sass:
  style: compressed
  

  